import type { Template } from "@/editor/types";

const now = 1700000000000;

export const DEMO_TEMPLATES: Template[] = [
  {
    id: "demo-minimal",
    name: "Clean Minimal",
    sizeId: "1:1",
    width: 1080,
    height: 1080,
    background: "#ffffff",
    layers: [
      {
        id: "minimal-bg",
        type: "shape",
        name: "Backdrop",
        x: 0,
        y: 0,
        w: 1080,
        h: 1080,
        rotation: 0,
        z: 0,
        visible: true,
        locked: false,
        style: { background: "#ffffff", borderRadius: 0 },
      },
      {
        id: "minimal-image",
        type: "product-image",
        name: "Product Image",
        x: 80,
        y: 70,
        w: 920,
        h: 740,
        rotation: 0,
        z: 1,
        visible: true,
        locked: false,
        style: { background: "#faf9f6", borderRadius: 32 },
        objectFit: "contain",
      },
      {
        id: "minimal-vendor",
        type: "text",
        name: "Vendor",
        x: 80,
        y: 830,
        w: 920,
        h: 36,
        rotation: 0,
        z: 2,
        visible: true,
        locked: false,
        style: {
          color: "#8a8a8a",
          fontSize: 26,
          fontWeight: 600,
          textAlign: "center",
          textTransform: "uppercase",
          letterSpacing: 0.14,
        },
        content: "{{vendor}}",
      },
      {
        id: "minimal-title",
        type: "text",
        name: "Title",
        x: 80,
        y: 866,
        w: 920,
        h: 80,
        rotation: 0,
        z: 3,
        visible: true,
        locked: false,
        style: { color: "#141414", fontSize: 44, fontWeight: 700, textAlign: "center", lineHeight: 1.1 },
        content: "{{title}}",
      },
      {
        id: "minimal-price",
        type: "badge",
        name: "Price Badge",
        x: 420,
        y: 956,
        w: 240,
        h: 64,
        rotation: 0,
        z: 4,
        visible: true,
        locked: false,
        style: { background: "#111111", color: "#ffffff", fontSize: 32, fontWeight: 700, borderRadius: 999, textAlign: "center" },
        content: "{{price}}",
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "demo-dark",
    name: "Premium Dark",
    sizeId: "1:1",
    width: 1080,
    height: 1080,
    background: "#0c0c0e",
    layers: [
      {
        id: "dark-image",
        type: "product-image",
        name: "Product Image",
        x: 60,
        y: 60,
        w: 960,
        h: 720,
        rotation: 0,
        z: 1,
        visible: true,
        locked: false,
        style: { background: "#17171a", borderRadius: 28 },
        objectFit: "contain",
      },
      {
        id: "dark-rule",
        type: "shape",
        name: "Gold rule",
        x: 500,
        y: 812,
        w: 80,
        h: 4,
        rotation: 0,
        z: 2,
        visible: true,
        locked: false,
        style: { background: "#c9a96a", borderRadius: 999 },
      },
      {
        id: "dark-vendor",
        type: "text",
        name: "Vendor",
        x: 80,
        y: 828,
        w: 920,
        h: 32,
        rotation: 0,
        z: 3,
        visible: true,
        locked: false,
        style: { color: "#c9a96a", fontSize: 24, fontWeight: 700, textAlign: "center", textTransform: "uppercase", letterSpacing: 0.2 },
        content: "{{vendor}}",
      },
      {
        id: "dark-title",
        type: "text",
        name: "Title",
        x: 80,
        y: 862,
        w: 920,
        h: 84,
        rotation: 0,
        z: 4,
        visible: true,
        locked: false,
        style: { color: "#fafafa", fontSize: 46, fontWeight: 700, textAlign: "center", lineHeight: 1.1 },
        content: "{{title}}",
      },
      {
        id: "dark-price",
        type: "badge",
        name: "Price Badge",
        x: 410,
        y: 958,
        w: 260,
        h: 66,
        rotation: 0,
        z: 5,
        visible: true,
        locked: false,
        style: { background: "#f5f5f4", color: "#0c0c0e", fontSize: 32, fontWeight: 800, borderRadius: 999, textAlign: "center" },
        content: "{{price}}",
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "demo-sale",
    name: "Sale Pop",
    sizeId: "1:1",
    width: 1080,
    height: 1080,
    background: "#fff7ed",
    layers: [
      {
        id: "sale-image",
        type: "product-image",
        name: "Product Image",
        x: 80,
        y: 120,
        w: 920,
        h: 690,
        rotation: 0,
        z: 1,
        visible: true,
        locked: false,
        style: { background: "#ffffff", borderRadius: 32 },
        objectFit: "contain",
      },
      {
        id: "sale-badge",
        type: "badge",
        name: "Sale Badge",
        x: 80,
        y: 80,
        w: 260,
        h: 60,
        rotation: -4,
        z: 5,
        visible: true,
        locked: false,
        style: { background: "#dc2626", color: "#ffffff", fontSize: 30, fontWeight: 800, borderRadius: 14, textAlign: "center", textTransform: "uppercase" },
        content: "SALE",
      },
      {
        id: "sale-title",
        type: "text",
        name: "Title",
        x: 80,
        y: 830,
        w: 920,
        h: 80,
        rotation: 0,
        z: 2,
        visible: true,
        locked: false,
        style: { color: "#1c1917", fontSize: 44, fontWeight: 800, textAlign: "center", lineHeight: 1.1 },
        content: "{{title}}",
      },
      {
        id: "sale-sub",
        type: "text",
        name: "Vendor line",
        x: 80,
        y: 908,
        w: 920,
        h: 32,
        rotation: 0,
        z: 3,
        visible: true,
        locked: false,
        style: { color: "#78716c", fontSize: 26, fontWeight: 600, textAlign: "center" },
        content: "{{vendor}}",
      },
      {
        id: "sale-price",
        type: "badge",
        name: "Price Badge",
        x: 420,
        y: 950,
        w: 240,
        h: 68,
        rotation: 0,
        z: 4,
        visible: true,
        locked: false,
        style: { background: "#111111", color: "#ffffff", fontSize: 33, fontWeight: 800, borderRadius: 999, textAlign: "center" },
        content: "{{price}}",
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
];

export const DEMO_TEMPLATE_IDS = DEMO_TEMPLATES.map((t) => t.id);
