// Embeds @fontsource Inter latin woff files as base64 so the server PNG
// route can pass real font data to ImageResponse/Satori without a runtime
// network fetch. Regenerate with: node scripts/embed-fonts.mjs
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const weights = [400, 600, 700];
const entries = weights.map((weight) => {
  const file = path.join(root, `node_modules/@fontsource/inter/files/inter-latin-${weight}-normal.woff`);
  const bytes = fs.readFileSync(file);
  return `  { weight: ${weight}, base64: "${bytes.toString("base64")}" },`;
});

const output = `// Generated by scripts/embed-fonts.mjs from @fontsource/inter (OFL license).
// Do not edit by hand. Latin-subset woff bytes for server PNG rendering.
export type EmbeddedFont = { weight: 400 | 600 | 700; base64: string };

export const INTER_FONTS: EmbeddedFont[] = [
${entries.join("\n")}
];

function decode(base64: string): ArrayBuffer {
  const binary = Buffer.from(base64, "base64");
  return binary.buffer.slice(binary.byteOffset, binary.byteOffset + binary.byteLength);
}

/** Satori/ImageResponse font descriptors for the bundled Inter family. */
export function interFonts(): { name: string; data: ArrayBuffer; weight: 400 | 600 | 700; style: "normal" }[] {
  return INTER_FONTS.map((font) => ({ name: "Inter", data: decode(font.base64), weight: font.weight, style: "normal" as const }));
}
`;

const destination = path.join(root, "src/editor/fonts.ts");
fs.writeFileSync(destination, output + "\n");
console.log(`Embedded ${weights.length} Inter weights into src/editor/fonts.ts`);
